from pathlib import Path
import json,sys
root=Path(__file__).resolve().parents[1]
errors=[]
def check(cond,msg):
    if not cond: errors.append(msg)
index=(root/'index.html').read_text()
app=(root/'assets/app.v0361.js').read_text()
worker=(root/'worker/src/index.js').read_text()
rules=(root/'rules/PROJECT_RULES.md').read_text()
check('VulkanScope Database <strong>0.36.1</strong>' in index,'index version')
check('site.v0360.css' in index and 'app.v0361.js' in index and 'config.js?v=0361' in index,'cache-busted asset refs')
check("connect-src 'self' https://vulkanscope-database-api.vulkanscope.workers.dev" in index,'CSP API pin')
check('Database 0.36.1' in app,'frontend version')
check('fetchJsonBounded' in app and '20000' in app and '4194304' in app,'bounded frontend API reads')
check('seenCursors' in app and 'Math.min(4,queue.length)' in app,'cursor/concurrency bounds')
check('v.detailedProperties=d.detailedProperties.map' in app and 'v.limits=d.limits.map' in app,'structured property/limit authority')
check("aggregateEntryLists(r=>r.detailedProperties||[]" in app,'properties aggregate separated')
check("aggregateEntryLists(r=>r.limits||[])" in app,'limits aggregate separated')
check("Properties (${(r.detailedProperties||[]).length})" in app,'detail property count separated')
check("Limits (${(r.limits||[]).length})" in app,'detail limit count separated')
check("(r.detailedProperties||[]).map" in app and "(r.limits||[]).map" in app,'detail tables separated')
check("normalizerVersion:11" in worker,'normalizer version')
check('detailedProperties=[],limits=[]' in worker,'worker separate fallback arrays')
check('tr?.schemaVersion===3&&d' in worker,'worker structured override')
check("publishedVulkanSpec:'Vulkan 1.4.360 (2026-08-14)'" in worker,'published spec metadata')
check('VulkanScope producer/query baseline 1.4.360' in worker,'producer baseline metadata')
check('cross-origin-resource-policy' in worker and 'cross-origin-opener-policy' in worker and 'content-security-policy' in worker,'API response security headers')
check("'clientip'" in worker and 'normalizedKey' in worker and 'hasSensitiveKey' in worker,'privacy key filter')
check('2*1024*1024' in worker and 'readBoundedBody' in worker,'streaming body bound')
check('Release 0.35.9 Display & HDR / ABI / home-metric parity' in rules and 'Release 0.36.0 luminance-unit typography parity' in rules and 'Release 0.36.1 VulkanScope 0.34.1 complete-report parity' in rules,'release rules')
json.loads((root/'report.schema.json').read_text())
json.loads((root/'data/index.json').read_text())
check("['display','Display & HDR']" in app,'Display & HDR navigation label')
check('reportSupportedAbis' in app and 'supportedDeviceAbis' in app,'supported ABI presentation')
check('luminanceDisplay' in app and 'cd/m²' in app,'luminance unit presentation')
check("metric('Compatible producers'" in app,'compatible producers metric')
check("producerQueryBaseline:meta?.producerQueryBaseline" in app and "compatibleProducer:meta?.compatibleProducer" in app,'API producer metadata propagation')
check("VulkanScope 0.34.1 · Vulkan 1.4.360" in worker,'current producer metadata')
if errors:
    print('AUDIT FAIL')
    for e in errors: print('-',e)
    sys.exit(1)
check('luminance-unit' in app,'luminance markup helper')
check('.luminance-unit{white-space:nowrap;color:var(--muted);font-size:.92em}' in (root/'assets/site.v0360.css').read_text(),'luminance typography')
print('VulkanScope Database 0.36.1 audit: PASS')
