from pathlib import Path
import json,subprocess,shutil,sys
root=Path(__file__).resolve().parents[1]
errors=[]
def check(cond,msg):
    if not cond: errors.append(msg)
index=(root/'index.html').read_text(encoding='utf-8')
app=(root/'assets/app.v0370.js').read_text(encoding='utf-8')
worker=(root/'worker/src/index.js').read_text(encoding='utf-8')
rules=(root/'rules/PROJECT_RULES.md').read_text(encoding='utf-8')
check('VulkanScope Database <strong>0.37.0</strong>' in index,'index version')
check('site.v0362.css' in index and 'app.v0370.js' in index and 'config.js?v=0370' in index,'cache-busted asset refs')
check("connect-src 'self' https://vulkanscope-database-api.vulkanscope.workers.dev" in index,'CSP API pin')
check('Database 0.37.0' in app,'frontend version')
check('VulkanScope 0.41.0 · Vulkan 1.4.360' in app,'frontend producer baseline')
check('fetchJsonBounded' in app and '20000' in app and '4194304' in app,'bounded frontend API reads')
check('seenCursors' in app and 'Math.min(4,queue.length)' in app,'cursor/concurrency bounds')
check('v.detailedProperties=d.detailedProperties.map' in app and 'v.limits=d.limits.map' in app,'structured property/limit authority')
check("aggregateEntryLists(r=>r.detailedProperties||[]" in app,'properties aggregate separated')
check("aggregateEntryLists(r=>r.limits||[])" in app,'limits aggregate separated')
check("Properties (${(r.detailedProperties||[]).length})" in app,'detail property count separated')
check("Limits (${(r.limits||[]).length})" in app,'detail limit count separated')
check("(r.detailedProperties||[]).map" in app and "(r.limits||[]).map" in app,'detail tables separated')
check('normalizerVersion:13' in worker,'normalizer version')
check('detailedProperties=[],limits=[]' in worker,'worker separate fallback arrays')
check('tr?.schemaVersion===3&&d' in worker,'worker structured override')
check("publishedVulkanSpec:'Vulkan 1.4.360 (2026-08-14)'" in worker,'published spec metadata')
check('VulkanScope producer/query baseline 1.4.360' in worker,'producer baseline metadata')
check('VulkanScope 0.41.0 · Vulkan 1.4.360' in worker,'current producer metadata')
for token in ['producerVersion=p=>','supportedProducer=p=>','currentProducerIdentity=p=>','validSecurityPatch=p=>','applicationAbiConsistent=p=>',"p.application.version!=='0.41.0'||p.application.versionCode===410"]:
    check(token in worker,f'producer-contract {token}')
check('cross-origin-resource-policy' in worker and 'cross-origin-opener-policy' in worker and 'content-security-policy' in worker,'API response security headers')
check("'clientip'" in worker and 'normalizedKey' in worker and 'hasSensitiveKey' in worker,'privacy key filter')
check('2*1024*1024' in worker and 'readBoundedBody' in worker,'streaming body bound')
for token in ['Release 0.35.9 Display & HDR / ABI / home-metric parity','Release 0.36.0 luminance-unit typography parity','Release 0.36.2 VulkanScope 0.34.2 complete-report parity','Release 0.36.3 technical-differences compare filter','Release 0.37.0 VulkanScope 0.41.0 trends and permalink requirements']:
    check(token in rules,f'release rule {token}')
check((root/'rules/0.37.0_VULKANSCOPE_0.41.0_TRENDS_PERMALINK_AUDIT.md').is_file(),'release audit document')
json.loads((root/'report.schema.json').read_text(encoding='utf-8'))
static=json.loads((root/'data/index.json').read_text(encoding='utf-8'))
check(static.get('databaseVersion')=='0.37.0','static database version')
check(static.get('normalizerVersion')==13,'static normalizer')
check(static.get('producerQueryBaseline')=='VulkanScope 0.41.0 · Vulkan 1.4.360','static producer baseline')
workflow=(root/'.github/workflows/pages.yml').read_text(encoding='utf-8')
check('node --check assets/app.v0370.js' in workflow,'workflow frontend check')
wr=json.loads((root/'worker/wrangler.jsonc').read_text(encoding='utf-8'))
check(wr.get('compatibility_date')=='2026-08-23','worker compatibility date')
check(wr.get('account_id')=='ccf3de9d3f2a4394af2fb7be7fd5bbf4','Cloudflare account pin')
dbs=wr.get('d1_databases',[])
check(bool(dbs) and dbs[0].get('binding')=='DB' and dbs[0].get('database_id')=='8fa65ef5-701d-4110-993d-87381f9763ab','D1 pin')
pkg=json.loads((root/'worker/package.json').read_text(encoding='utf-8'))
check(pkg.get('version')=='0.37.0','worker package version')
check(pkg.get('devDependencies',{}).get('wrangler')=='4.125.0','Wrangler pin')
for key in ['predeploy','premigrate','premigrations:list','pred1:count']:
    check('verify:account' in pkg.get('scripts',{}).get(key,''),f'account guard {key}')
for token in ['Technical differences only','technicalCompareEntry','applicationVersion','applicationVersionCode','submittedAt']:
    check(token in app,f'technical compare {token}')
for token in ['Submission trends','renderTrends','Loaded-submission share','market share. Extension percentages','routeReportUrl','routeCompareUrl','applyInitialRoute','Share comparison link','Share permalink']:
    check(token in app,f'0.37.0 frontend {token}')
check(wr.get('observability',{}).get('enabled') is True,'Cloudflare observability enabled')
check(wr.get('observability',{}).get('logs',{}).get('head_sampling_rate')==0.1,'Cloudflare log sampling')
check(wr.get('observability',{}).get('traces',{}).get('head_sampling_rate')==0.01,'Cloudflare trace sampling')
node=shutil.which('node')
if node:
    for f in [root/'assets/app.v0370.js',root/'worker/src/index.js',root/'worker/tests/contract.mjs']:
        r=subprocess.run([node,'--check',str(f)],capture_output=True,text=True)
        if r.returncode: errors.append(f'node-check {f.relative_to(root)}: {r.stderr.strip()}')
    r=subprocess.run([node,str(root/'worker/tests/contract.mjs')],capture_output=True,text=True,cwd=root/'worker')
    if r.returncode: errors.append(f'worker-contract: {r.stdout.strip()} {r.stderr.strip()}')
if errors:
    print('\n'.join(errors));sys.exit(1)
print('VulkanScope Database 0.37.0 audit: PASS')
