from pathlib import Path
import subprocess,sys,tempfile,sqlite3
root=Path(__file__).resolve().parents[1]

def run(*cmd,cwd=root):
    print('+',' '.join(map(str,cmd)))
    r=subprocess.run(cmd,cwd=cwd,text=True)
    if r.returncode: raise SystemExit(r.returncode)

run(sys.executable,'tools/test_utf8_text_io.py')
run(sys.executable,'tools/verify_optional_npm_lock.py')
run(sys.executable,'tools/verify_vulkan_registry.py')
run('node','tools/test_report_text_identity.mjs')
run(sys.executable,'tools/repair_repository.py','--apply')
run(sys.executable,'tools/repair_repository.py','--check')
run(sys.executable,'tools/verify_regression_contract.py')
run(sys.executable,'tools/verify_1_4_6_submission_floor.py')
run(sys.executable,'tools/test_1_4_6_submission_floor_negative_mutations.py')
run(sys.executable,'tools/audit_database.py','--source-tree','.')
run('node','--check','assets/app.v1406.js')
run('node','--check','assets/browser-compat.v1406.js')
run('node','--check','assets/encyclopedia.v03924.js')
run('node','--check','worker/src/index.js')
run('node','--check','worker/tests/contract.mjs')
run('node','worker/tests/contract.mjs')
con=sqlite3.connect(':memory:')
for migration in sorted((root/'worker/migrations').glob('*.sql')): con.executescript(migration.read_text(encoding='utf-8'))
assert con.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='report_payload_chunks'").fetchone()
print('PASS D1 migration chain')
with tempfile.TemporaryDirectory(prefix='vulkanscope-db-pages-') as td:
    run(sys.executable,'tools/build_pages_artifact.py',td)
    staged=Path(td)
    assert (staged/'assets/app.v1406.js').is_file()
    assert (staged/'assets/app.v1405.js').is_file()
    assert not (staged/'assets/app.v1404.js').exists()
    assert (staged/'assets/release-bootstrap.v1406.js').is_file()
    assert (staged/'assets/release-bootstrap.v1405.js').is_file()
    assert not (staged/'assets/release-bootstrap.v1404.js').exists()
    assert (staged/'assets/browser-compat.v1406.js').is_file()
    assert (staged/'assets/browser-compat.v1405.js').is_file()
    assert not (staged/'assets/browser-compat.v1404.js').exists()
    assert (staged/'assets/site.v0390.css').is_file()
    assert (staged/'assets/site.v1308.css').is_file()
    assert (staged/'assets/site.v1309.css').is_file()
    assert (staged/'assets/site.v1400.css').is_file()
    assert (staged/'assets/site.v1401.css').is_file()
    assert (staged/'assets/site.v1402.css').is_file()
    assert (staged/'assets/site.v1403.css').is_file()
    assert (staged/'assets/site.v1404.css').is_file()
    assert (staged/'assets/site.v1405.css').is_file()
    assert (staged/'assets/site.v1406.css').is_file()
    assert (staged/'assets/hdr/hdr10_plus_v1014.png').is_file()
    for name in ('google-chrome.v1307.svg','chromium.v1307.png','microsoft-edge.v1307.svg','firefox.v1307.svg','safari.v1307.svg','opera.v1307.svg','brave.v1307.svg','vivaldi.v1307.svg','samsung-browser.v1307.svg'):
        assert (staged/'assets/browser-logos'/name).is_file(), f'missing staged browser mark: {name}'
    for name in ('wrangler.md','sharp.md','esbuild.md','workerd.md','nodejs.md','python.md','browser-marks.md'):
        assert (staged/'licenses'/name).is_file(), f'missing staged license: {name}'
    assert not (staged/'worker').exists()
    assert not (staged/'rules').exists()
    marker=__import__('json').loads((staged/'data/release.json').read_text(encoding='utf-8'))
    assert marker.get('releaseReady') is False
    run(sys.executable,'tools/audit_database.py','--artifact-tree',td)
    run(sys.executable,'tools/mark_release_ready.py',td)
    run(sys.executable,'tools/audit_database.py','--artifact-tree',td,'--require-release-ready')
    print('PASS Pages allow-list + release-ready transition boundary')
print('VulkanScope Database 1.4.6 quality gate: PASS')
