from pathlib import Path
import subprocess,sys,tempfile,sqlite3
root=Path(__file__).resolve().parents[1]

def run(*cmd,cwd=root):
    print('+',' '.join(map(str,cmd)))
    r=subprocess.run(cmd,cwd=cwd,text=True)
    if r.returncode: raise SystemExit(r.returncode)

run(sys.executable,'tools/test_utf8_text_io.py')
run(sys.executable,'tools/verify_optional_npm_lock.py')
run(sys.executable,'tools/verify_vulkan_registry.py')
run(sys.executable,'tools/verify_vulkanscope_04132.py')
run('node','tools/test_report_text_identity.mjs')
run(sys.executable,'tools/repair_repository.py','--check')
if (root/'regression/0.39.25_to_0.39.26_contract.json').exists(): run(sys.executable,'tools/verify_regression_contract.py')
run(sys.executable,'tools/test_existing_repo_overlay.py')
run(sys.executable,'tools/audit_database.py','--source-tree','.')
run(sys.executable,'tools/test_audit_hygiene.py')
run('node','--check','assets/app.v03926.js')
run('node','--check','assets/encyclopedia.v03924.js')
run('node','tools/test_routes.mjs')
run('node','tools/test_compare_contract.mjs')
run('node','tools/test_compare_04141_compat.mjs')
run('node','tools/test_compare_04141_negative_mutations.mjs')
run('node','tools/test_surface_compare_04142.mjs')
run('node','tools/test_surface_compare_04142_negative_mutations.mjs')
run('node','tools/test_producer_baseline_04146.mjs')
run('node','tools/test_producer_baseline_04146_negative_mutations.mjs')
run(sys.executable,'tools/verify_0808_floor_loading_scroll.py')
run(sys.executable,'tools/test_0808_floor_loading_scroll_state_machine.py')
run(sys.executable,'tools/test_0808_floor_loading_scroll_negative_mutations.py')
run(sys.executable,'tools/verify_0809_floor_encyclopedia.py')
run(sys.executable,'tools/test_0809_floor_encyclopedia_state_machine.py')
run(sys.executable,'tools/test_0809_floor_encyclopedia_negative_mutations.py')
run(sys.executable,'tools/verify_vulkan_1_4_362_03924.py')
run(sys.executable,'tools/test_vulkan_1_4_362_03924_negative_mutations.py')
run(sys.executable,'tools/verify_03925_ui_coherence.py')
run(sys.executable,'tools/test_03925_ui_coherence_negative_mutations.py')
run(sys.executable,'tools/verify_03926_0812_submission_diagnostics.py')
run(sys.executable,'tools/test_03926_0812_submission_diagnostics_negative_mutations.py')
run('node','--check','worker/src/index.js')
run('node','--check','worker/tests/contract.mjs')
run('node','worker/tests/contract.mjs')
con=sqlite3.connect(':memory:')
for migration in sorted((root/'worker/migrations').glob('*.sql')): con.executescript(migration.read_text(encoding='utf-8'))
assert con.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='report_payload_chunks'").fetchone()
print('PASS D1 migration chain')
with tempfile.TemporaryDirectory(prefix='vulkanscope-db-pages-') as td:
    run(sys.executable,'tools/build_pages_artifact.py',td)
    run(sys.executable,'tools/audit_database.py','--artifact-tree',td)
print('VulkanScope Database quality gate: PASS')
