import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=process.argv[2]?path.resolve(process.argv[2]):path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const assets=fs.readdirSync(path.join(root,'assets')).filter(x=>/^app\.v\d+\.js$/.test(x)).sort();
if(!assets.length)throw new Error('frontend asset missing');
const source=fs.readFileSync(path.join(root,'assets',assets.at(-1)),'utf8');
const start=source.indexOf('const hostImageCopyCompareIdentity=');
const end=source.indexOf('function compareMap(r)',start);
if(start<0||end<0)throw new Error('compare identity block missing');
const block=source.slice(start,end)+'\nglobalThis.historicalPropertyFeatureCompareIdentity=historicalPropertyFeatureCompareIdentity;';
const sandbox={};
vm.createContext(sandbox);
vm.runInContext(block,sandbox);
const f=sandbox.historicalPropertyFeatureCompareIdentity;
const old={application:{version:'0.41.39'}};
const current={application:{version:'0.41.40'}};
const mapped=f(old,'FEATURES','VkPhysicalDeviceDescriptorIndexingProperties · quadDivergentImplicitLod','true','supported');
if(mapped.section!=='VkPhysicalDeviceDescriptorIndexingProperties'||mapped.name!=='quadDivergentImplicitLod'||mapped.value!=='true'||mapped.status!=='available')throw new Error('historical property-feature mapping failed');
const falseMapped=f(old,'FEATURES','VkPhysicalDeviceDescriptorIndexingProperties · quadDivergentImplicitLod','false','unsupported');
if(falseMapped.status!=='available'||falseMapped.value!=='false')throw new Error('false property value mapping failed');
const actualFeature=f(old,'FEATURES','VkPhysicalDeviceDescriptorIndexingFeatures · runtimeDescriptorArray','true','supported');
if(actualFeature.section!=='FEATURES')throw new Error('real feature was incorrectly remapped');
const nonBool=f(old,'FEATURES','VkPhysicalDeviceDescriptorIndexingProperties · maxUpdateAfterBindDescriptorsInAllPools','123','supported');
if(nonBool.section!=='FEATURES')throw new Error('non-boolean historical evidence was incorrectly remapped');
const currentNoRewrite=f(current,'FEATURES','VkPhysicalDeviceDescriptorIndexingProperties · quadDivergentImplicitLod','true','supported');
if(currentNoRewrite.section!=='FEATURES')throw new Error('current producer evidence was rewritten');
if(!source.includes("const visibleMetricLabel=diff?'Visible differences':'Visible fields'"))throw new Error('visible field/difference metric semantics missing');
if(!source.includes("const emptyText=diff?(technical?'No technical differences with the current filters.':'No differences with the current filters.'):'No fields match the current filters.'"))throw new Error('compare empty-state semantics missing');
console.log('PASS Database 0.39.16 historical compare compatibility');
