from pathlib import Path
import json, sys
root=Path(__file__).resolve().parents[1]
def text(rel): return (root/rel).read_text(encoding='utf-8')
def need(cond,msg):
    if not cond: raise SystemExit('FAIL '+msg)
app=text('assets/app.v1407.js')
worker=text('worker/src/index.js')
preload=text('tools/build_preload_snapshot.py')
index=text('index.html')
marker=json.loads(text('data/release.json'))
static=json.loads(text('data/index.json'))
rules=text('rules/PROJECT_RULES.md')
repair=text('tools/repair_repository.py')
pages=text('tools/build_pages_artifact.py')
need(marker=={'schemaVersion':2,'databaseVersion':'1.4.7','releaseReady':False,'appAsset':'assets/app.v1407.js','cacheKey':'1407'},'1.4.7 release marker mismatch')
for token in ['./assets/site.v1407.css?v=1407','./assets/release-bootstrap.v1407.js?v=1407','./assets/browser-compat.v1407.js?v=1407','./assets/app.v1407.js?v=1407','./config.js?v=1407','VulkanScope Database <strong>1.4.7</strong>']:
    need(token in index,f'index current identity missing: {token}')
need("const DATABASE_VERSION='1.4.7'" in app,'frontend Database version mismatch')
need("CURRENT_PRODUCER_QUERY_BASELINE='VulkanScope 1.4.3 · Vulkan 1.4.362'" in app,'frontend current producer baseline constant missing')
need("CURRENT_COMPATIBLE_PRODUCER='VulkanScope 1.4.3+ · schema 2 / technical report 3'" in app,'frontend compatible-producer constant missing')
need('producerQueryBaseline:CURRENT_PRODUCER_QUERY_BASELINE' in app,'frontend still trusts live producerQueryBaseline metadata')
need('compatibleProducer:CURRENT_COMPATIBLE_PRODUCER' in app,'frontend still trusts live compatibleProducer metadata')
need("meta?.producerQueryBaseline||" not in app,'obsolete live producer baseline fallback remains')
need("meta?.compatibleProducer||" not in app,'obsolete live compatible-producer fallback remains')
need("'producerQueryBaseline': 'VulkanScope 1.4.3 · Vulkan 1.4.362'" in preload,'preload producer baseline is not release-authored')
need("'compatibleProducer': 'VulkanScope 1.4.3+ · schema 2 / technical report 3'" in preload,'preload compatible-producer metadata still inherits live Worker')
need("meta.get('compatibleProducer'" not in preload,'stale Worker compatibleProducer can still enter preload')
need("const producerAtLeast1403" in worker and "const supportedProducer=p=>producerAtLeast1403(p)" in worker,'Worker 1.4.3 floor missing')
need('VulkanScope 1.4.3 or newer is required for new submissions' in worker,'Worker 1.4.3 rejection missing')
for token in ["databaseReleaseVersion:'1.4.7'","workerReleaseVersion:'1.4.7'",'VulkanScope 1.4.3 · Vulkan 1.4.362','VulkanScope 1.4.3+ · schema 2 / technical report 3']:
    need(token in worker,f'Worker current metadata missing: {token}')
need(static.get('databaseVersion')=='1.4.7','static index Database version mismatch')
need(static.get('producerQueryBaseline')=='VulkanScope 1.4.3 · Vulkan 1.4.362','static producer baseline mismatch')
need(static.get('compatibleProducer')=='VulkanScope 1.4.3+ · schema 2 / technical report 3','static compatible producer mismatch')
need('## Release 1.4.7 producer-floor metadata coherence requirements' in rules,'1.4.7 rules section missing')
need("CURRENT_APP = 'app.v1407.js'" in repair,'repair current app mismatch')
need("PREDECESSOR_BRIDGE = {'app.v1406.js','browser-compat.v1406.js','release-bootstrap.v1406.js'}" in repair,'1.4.7 predecessor bridge mismatch')
need("'assets/app.v1406.js'" in pages and "'assets/app.v1407.js'" in pages and "'assets/app.v1405.js'" not in pages,'Pages current/predecessor bridge mismatch')
need((root/'rules/1.4.7_FLOOR_METADATA_COHERENCE_AUDIT.md').is_file(),'1.4.7 audit file missing')
print('PASS Database 1.4.7 producer-floor metadata coherence contract')
