from pathlib import Path
import json, hashlib
root=Path(__file__).resolve().parents[1]
def text(rel): return (root/rel).read_text(encoding='utf-8')
def need(cond,msg):
    if not cond: raise SystemExit('FAIL '+msg)
app=text('assets/app.v1408.js')
worker=text('worker/src/index.js')
preload=text('tools/build_preload_snapshot.py')
index=text('index.html')
marker=json.loads(text('data/release.json'))
static=json.loads(text('data/index.json'))
lock=json.loads(text('registry/registry_lock.json'))
schema=json.loads(text('report.schema.json'))
rules=text('rules/PROJECT_RULES.md')
repair=text('tools/repair_repository.py')
pages=text('tools/build_pages_artifact.py')
ency=text('assets/encyclopedia.v1408.js')
need(marker=={'schemaVersion':2,'databaseVersion':'1.4.8','releaseReady':False,'appAsset':'assets/app.v1408.js','cacheKey':'1408'},'1.4.8 release marker mismatch')
for token in ['./assets/site.v1408.css?v=1408','./assets/release-bootstrap.v1408.js?v=1408','./assets/browser-compat.v1408.js?v=1408','./assets/app.v1408.js?v=1408','./config.js?v=1408','./assets/encyclopedia.v1408.js','VulkanScope Database <strong>1.4.8</strong>']:
    need(token in index,f'index current identity missing: {token}')
need("const DATABASE_VERSION='1.4.8'" in app,'frontend Database version mismatch')
need("CURRENT_PRODUCER_QUERY_BASELINE='VulkanScope 2.0.6 · Vulkan 1.4.364'" in app,'frontend producer/query baseline mismatch')
need("CURRENT_COMPATIBLE_PRODUCER='VulkanScope 2.0.6+ · schema 2 / technical report 3'" in app,'frontend compatible-producer contract mismatch')
need('producerQueryBaseline:CURRENT_PRODUCER_QUERY_BASELINE' in app and 'compatibleProducer:CURRENT_COMPATIBLE_PRODUCER' in app,'frontend release-authored metadata pin missing')
need("'producerQueryBaseline': 'VulkanScope 2.0.6 · Vulkan 1.4.364'" in preload,'preload producer baseline mismatch')
need("'compatibleProducer': 'VulkanScope 2.0.6+ · schema 2 / technical report 3'" in preload,'preload compatible producer mismatch')
need("meta.get('compatibleProducer'" not in preload,'stale live Worker compatibleProducer can enter preload')
need('const producerAtLeast2006' in worker and 'const supportedProducer=p=>producerAtLeast2006(p)' in worker,'Worker 2.0.6 submission floor missing')
need('VulkanScope 2.0.6 or newer is required for new submissions' in worker,'Worker 2.0.6 floor rejection missing')
need('if(v.major===2)return p.application.versionCode===2000+v.minor*100+v.patch' in worker,'2.x semantic-version/versionCode identity mapping missing')
need('return false};const validCurrentQueryDiagnostics' in worker,'unknown producer identity does not fail closed')
for key in ['platform','chromeOsArcRuntime','androidPcFormFactor','freeformWindowManagement','googlebookEnvironmentEvidence','googlebookOsVersion','hostOsVersion']:
    need(key in worker,f'Worker 2.0.6 device field missing: {key}')
need('const validCurrentDeviceEnvironment=' in worker and "validation='device_environment'" in worker,'2.0.6 device-environment validation missing')
for token in ["databaseReleaseVersion:'1.4.8'","workerReleaseVersion:'1.4.8'",'VulkanScope 2.0.6 · Vulkan 1.4.364','VulkanScope 2.0.6+ · schema 2 / technical report 3','Vulkan 1.4.364 (2026-09-25)']:
    need(token in worker,f'Worker current metadata missing: {token}')
need("producerAtLeast2006(p)?'1.4.364':producerAtLeast08010(p)?'1.4.362':'1.4.361'" in worker,'2.0.6 registry contract selector missing')
need("producerAtLeast2006(p)?'vulkan_1_4_364_registry_contract'" in worker,'2.0.6 registry validation classification missing')
need(static.get('databaseVersion')=='1.4.8','static index Database version mismatch')
need(static.get('publishedVulkanSpec')=='Vulkan 1.4.364 (2026-09-25)','static published Vulkan specification mismatch')
need(static.get('vulkanRegistryBaseline')=='VulkanScope producer/query baseline 1.4.364','static registry baseline mismatch')
need(static.get('producerQueryBaseline')=='VulkanScope 2.0.6 · Vulkan 1.4.364','static producer baseline mismatch')
need(static.get('compatibleProducer')=='VulkanScope 2.0.6+ · schema 2 / technical report 3','static compatible producer mismatch')
need(lock.get('apiVersion')=='1.4.364' and lock.get('headerVersion')==364,'registry/header version lock mismatch')
need(lock.get('registeredVulkanExtensionCount')==477,'registered extension census mismatch')
need(lock.get('requiredCurrentExtension')=='VK_INTEL_device_info','current registry extension sentinel mismatch')
need(lock.get('requiredCurrentStruct')=='VkPhysicalDeviceInfoPropertiesINTEL','current registry struct sentinel mismatch')
reg=root/lock['bundledRegistryPath']
need(reg.is_file() and hashlib.sha256(reg.read_bytes()).hexdigest()==lock.get('registrySha256'),'bundled registry SHA-256 mismatch')
need('VK_INTEL_device_info' in ency and 'VkPhysicalDeviceInfoPropertiesINTEL' in ency,'1.4.364 encyclopedia sentinel coverage missing')
app_schema=schema['properties']['application']['properties']
need(app_schema['versionCode'].get('minimum')==2006,'report schema versionCode floor mismatch')
need('2\\.' in app_schema['version'].get('pattern','') and '0\\.(?:[6-9]' in app_schema['version'].get('pattern',''),'report schema 2.0.6 semantic floor mismatch')
device_schema=schema['properties']['device']
expected_device={'platform','chromeOsArcRuntime','androidPcFormFactor','freeformWindowManagement','googlebookEnvironmentEvidence','googlebookOsVersion','hostOsVersion','manufacturer','brand','model','device','product','androidRelease','sdk','securityPatch'}
need(set(device_schema.get('required',[]))==expected_device,'report schema device required-field set mismatch')
need(device_schema.get('additionalProperties') is False,'report schema device envelope must be exact')
need(schema.get('properties',{}).get('technicalReport',{}).get('type')=='object','technical report schema object missing')
need('## Release 1.4.8 VulkanScope 2.0.6 compatibility and submission-floor requirements' in rules,'1.4.8 rules section missing')
need("CURRENT_APP = 'app.v1408.js'" in repair,'repair current app mismatch')
need("PREDECESSOR_BRIDGE = {'app.v1407.js','browser-compat.v1407.js','release-bootstrap.v1407.js'}" in repair,'1.4.8 predecessor bridge mismatch')
need("'assets/app.v1407.js'" in pages and "'assets/app.v1408.js'" in pages and "'assets/app.v1406.js'" not in pages,'Pages current/predecessor app bridge mismatch')
need((root/'rules/1.4.8_VULKANSCOPE_2_0_6_COMPATIBILITY_AUDIT.md').is_file(),'1.4.8 audit file missing')
print('PASS Database 1.4.8 VulkanScope 2.0.6 compatibility/submission-floor contract')
